SELECT 
	TABLE_SCHEMA AS database_name, 
	TABLE_ENGINE AS engine,
	SUM(count)   AS number_of_tables 
FROM (
	SELECT 
		TABLE_SCHEMA,
		COALESCE(ENGINE,'MyISAM') AS TABLE_ENGINE,
		COUNT(*) AS COUNT
	FROM 
		information_schema.TABLES
	GROUP by TABLE_SCHEMA,TABLE_ENGINE 
) a
GROUP by TABLE_SCHEMA,TABLE_ENGINE
